### ISSUE TITLE
Subdomain problem

### ISSUE THREAD

**Issue by MingyaoLiu** [mezzoblue/PaintbrushJS#6]
I was testing PaintbrushJS, and i found a small problem
I use images from wordpress in subdomain, and PaintJS won't work.
For example:
my domain: zsm.me, subdomain tech.zsm.me
' http://tech.zsm.me/xxxxxxxx.png ' won't work
but
' http://www.zsm.me/tech/xxxxxxxx.png ' works
however .jpg file won't work in any case, but it works if path is http://www.zsm.me/xxxxx.jpg
any clue? is it because of the path or something else? any solution?

**Comment by mezzoblue** [comment]
Well known same origin policy in most browsers. https://github.com/mezzoblue/PaintbrushJS/wiki/known-issues see point 5. There is no workaround.
